README.md
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Readme add community, contributing and code of conduct.
=> docs: readme add community, contributing and code of conduct

.github/workflows/lint.yml, go.mod
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Update golang version to 1.19.
=> feat: update golang version to 1.19

.github/workflows/lint.yml
Signed-off-by: Gaius <gaius.qi@gmail.com>
- Rename cargo clippy actions
=> chore: rename cargo clippy actions

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/custom.md, .github/ISSUE_TEMPLATE/feature-request.md
Signed-off-by: Gaius <gaius.qi@gmail.com>
=> chore: update issue template

Cargo.toml, src/dfdaemon.rs, src/manager.rs, src/scheduler.rs, src/security.rs
=> feat: update tonic-build to v0.9.0

.github/workflows/lint.yml, README.md
=> docs: optimize Community description in README.md

pkg/apis/manager/v1/manager.proto, pkg/apis/manager/v2/manager.proto, proto/manager.proto
=> fix: proto style

Cargo.toml
=> chore: add description to rust crate

Cargo.toml
=> chore: update crate version to v1.9.7

Cargo.toml
=> chore: add protoc dependencies in Cargo.toml

Cargo.toml
=> chore: remove protoc

Cargo.toml, go.mod, go.sum, pkg/apis/cdnsystem/v1/mocks/cdnsystem_mock.go, pkg/apis/dfdaemon/v1/mocks/dfdaemon_mock.go, pkg/apis/dfdaemon/v2/mocks/dfdaemon_mock.go, pkg/apis/inference/v1/mocks/grpc_service_mock.go, pkg/apis/manager/v1/mocks/manager_mock.go, pkg/apis/manager/v2/mocks/manager_mock.go, pkg/apis/scheduler/v1/mocks/scheduler_mock.go, pkg/apis/scheduler/v2/mocks/scheduler_mock.go, pkg/apis/trainer/v1/mocks/trainer_mock.go
=> feat: generate golang mock

Cargo.toml, build.rs
=> chore: update tonic and tokio version

Cargo.toml
=> chore: update cargo version to 2.0.23

Cargo.toml
=> chore: update crate version to 2.0.24

Cargo.toml, go.mod, go.sum
=> chore: update golang version to v1.21

Cargo.toml
=> chore: update cargo version to v2.0.95

pkg/apis/scheduler/v1/scheduler.proto
=> fix: typo in scheduler v1 proto

Cargo.lock, Cargo.toml, pkg/apis/dfdaemon/v2/mocks/dfdaemon_mock.go, pkg/apis/scheduler/v2/mocks/scheduler_mock.go
=> feat: generate mock code in scheduler

pkg/apis/manager/v1/manager.pb.go, pkg/apis/manager/v1/manager.proto
=> fix: comment error

Cargo.lock, Cargo.toml, pkg/apis/dfdaemon/v2/mocks/dfdaemon_mock.go, pkg/apis/scheduler/v2/mocks/scheduler_mock.go
=> feat: generate mocks

pkg/apis/common/v2/common.proto, proto/common.proto
=> feat: fixed the comments for PersistentCacheTask
